import { BSC_MAINNET, BSC_TESTNET, isTestnetOnlyToken } from './bsc';
import { DEPLOYED_TESTNET } from './deployedAddresses';
import { getContractAddress, getRuntimeMode } from './rpcConfig';

export { getContractAddress };

export function getUsdtAddress(): string {
  if (getRuntimeMode() === 'live') return BSC_MAINNET.usdt;
  const fromEnv = (process.env.EXPO_PUBLIC_USDT_ADDRESS || '').toLowerCase();
  if (fromEnv && isTestnetOnlyToken(fromEnv)) return fromEnv;
  if (fromEnv && fromEnv.startsWith('0x') && fromEnv !== BSC_MAINNET.usdt.toLowerCase()) {
    return fromEnv;
  }
  return DEPLOYED_TESTNET.usdt || BSC_TESTNET.usdt;
}

export const ERC20_ABI = [
  'function balanceOf(address owner) view returns (uint256)',
  'function allowance(address owner, address spender) view returns (uint256)',
  'function approve(address spender, uint256 amount) returns (bool)',
  'function decimals() view returns (uint8)',
  'function transfer(address to, uint256 amount) returns (bool)',
  'function transferFrom(address from, address to, uint256 amount) returns (bool)',
];

export const CONTRACT_ABI = [
  'function depositarLiquidez(address token, uint256 _monto)',
  'function retirarLiquidez(address token, uint256 amount)',
  'function solicitarPrestamo(address token, uint256 nivel)',
  'function pagarPrestamo(address token, uint256 _montoConInteres)',
  'function registrarHumanoConPadre(address _padre)',
  'function declararKyc()',
  'function setKycExigido(bool exigido)',
  'function kycDeclarado(address) view returns (bool)',
  'function kycExigido() view returns (bool)',
  'function proposeAdminAction(bytes data) returns (uint256 id)',
  'function confirmAdminAction(uint256 id)',
  'function executeAdminAction(uint256 id)',
  'function proposalCount() view returns (uint256)',
  'function proposals(uint256) view returns (address proposer, uint256 eta, bytes data, uint256 confirms, bool executed, bool cancelled)',
  'function ownerList(uint256) view returns (address)',
  'function requiredConfirmations() view returns (uint256)',
  'function addAdmin(address newAdmin)',
  'function removeAdmin(address admin)',
  'function setFeeCollector(address newCollector)',
  'function setRequiredConfirmations(uint256 _required)',
  'function setTokenConfig(address token, address feed, bool enabled)',
  'function setOwner(address newOwner)',
  'function setFundador(address next)',
  'function setFeeBP(uint256 _feeBP)',
  'function setNivel(uint256 id, uint256 montoPrestamo, uint256 plazo, uint256 tasaInteresBP)',
  'function setInterestModelParams(uint256 _tasaBaseBP, uint256 _puntoOptimoUtilBP, uint256 _pendiente1BP, uint256 _pendiente2BP)',
  'function setReputationParams(uint256 _puntosPago, uint256 _penalizacion, uint256 _thresholdGov)',
  'function setMorosidad(address usuario, bool moroso)',
  'function banWallet(address _addr, bool _banned)',
  'function despausarContrato()',
  'function setSecurityParams(uint256 _maxOriginationsPerWindow, uint256 _maxUtilizationBps)',
  'function feeBasisPoints() view returns (uint256)',
  'function BONO_ACTIVACION() view returns (uint256)',
  'function TIMELOCK_DELAY() view returns (uint256)',
  'function COOLDOWN_PRESTAMO() view returns (uint256)',
  'function esMoroso(address) view returns (bool)',
  'function blacklist(address) view returns (bool)',
  'function calcularTasaUtilizacion(address tokenAddress) view returns (uint256)',
  'function vincularIdentidad(bytes32 phoneHash, bytes32 deviceHash, uint256 deadline, uint8 v, bytes32 r, bytes32 s)',
  'function setIdentidadExigida(bool exigido)',
  'function setAttester(address next)',
  'function phoneHashOf(address) view returns (bytes32)',
  'function deviceHashOf(address) view returns (bytes32)',
  'function walletOfPhone(bytes32) view returns (address)',
  'function walletOfDevice(bytes32) view returns (address)',
  'function identidadExigida() view returns (bool)',
  'function attester() view returns (address)',
  'function cuentaDestruida(address) view returns (bool)',
  'function destruirCuenta(address token)',
  'function feeCollector() view returns (address)',
  'function fundador() view returns (address)',
  'function humanosVerificados(address) view returns (bool)',
  'function redGenealogica(address) view returns (address padre, bool bonoActivacionCobrado)',
  'function prestamosCerrados(address) view returns (uint256)',
  'function dispersionCongelada(address usuario) view returns (bool)',
  'function usuarios(address) view returns (uint256 nivelActual, uint256 montoActivo, uint256 vencimiento, bool enMora, address monedaActivo, uint256 tasaAplicadaBP)',
  'function obtenerHistorialUsuario(address usuario) view returns (uint256 puntosReputacion, bool moroso, uint256 pagadosATiempo, uint256 morosos, uint256 totalPenalizaciones)',
  'function obtenerRedReputacion(address usuario) view returns (uint256 puntos, uint256 bonosCobrados, uint256 umbral, uint256 bono, uint256 puntosPorReferido)',
  'function puntosRed(address) view returns (uint256)',
  'function PUNTOS_POR_REFERIDO() view returns (uint256)',
  'function UMBRAL_BONO_RED() view returns (uint256)',
  'function BONO_RED_USDT() view returns (uint256)',
  'function obtenerProgresoUsuario(address usuario) view returns (uint256 nivelActual, uint256 solicitudesCompletadas, uint256 ultimoPrestamoTimestamp)',
  'function hitoCobrado(address) view returns (uint256)',
  'function donado(address) view returns (uint256)',
  'function cobrarBonoHito(address token)',
  'function donar(address token, uint256 amount)',
  'function famaHermano() view returns (address)',
  'function pagarCanje(address token, address to, uint256 amount)',
  'function obtenerDeuda(address usuario) view returns (uint256 principal, uint256 interes, uint256 total, address token)',
  'function planPago(address) view returns (uint128 pagado, uint64 venceCuota, uint8 totales, uint8 pagadas, bool enPlazo)',
  'function valorLp(address user, address token) view returns (uint256)',
  'function owner() view returns (address)',
  'function admins(address) view returns (bool)',
  'function paused() view returns (bool)',
  'function pausarContrato()',
  'function niveles(uint256 id) view returns (uint256, uint256, uint256)',
  'function supportedToken(address) view returns (bool)',
  'function obtenerTasaInteresActual(address tokenAddress) view returns (uint256)',
  'function totalLiquidity(address) view returns (uint256)',
  'function outstandingLoans(address) view returns (uint256)',
  'function collectedFees(address) view returns (uint256)',
  'function retirarComisiones()',
  'function retirarComisionesToken(address token)',
  'function marcarMorosoSiVencido(address usuario)',
  'function liquidate(address deudor, address tokenAddress)',
  'event AfiliadoRegistrado(address indexed usuario, address indexed padre)',
  'event BonoActivacionPagado(address indexed padre, address indexed referido, uint256 monto, address indexed token)',
  'event BonoRedPagado(address indexed usuario, uint256 umbral, uint256 monto, address indexed token)',
  'event BonoHitoPagado(address indexed usuario, uint256 hito, uint256 monto, address indexed token)',
  'event Donacion(address indexed usuario, uint256 monto, address indexed token)',
  'event PuntosRed(address indexed usuario, uint256 puntos)',
  'event ComisionGeneracional(address indexed beneficiario, address indexed deudor, uint8 generacion, uint256 monto, address indexed token)',
  'event KycDeclarado(address indexed usuario)',
  'event KycExigidoUpdated(bool exigido)',
  'event IdentidadVinculada(address indexed usuario, bytes32 phoneHash, bytes32 deviceHash)',
  'event CuentaDestruida(address indexed usuario, address indexed token, uint256 confiscado)',
  'event PrestamoEmitido(address indexed usuario, uint256 monto, uint256 vencimiento, address indexed token)',
  'event PrestamoPagado(address indexed usuario, uint256 montoPrincipal, uint256 fee, address indexed token)',
  'event MorosityUpdated(address indexed usuario, bool esMoroso)',
  'event InteresDistribuido(address indexed deudor, address indexed token, uint256 interes, uint256 comisionesRed, uint256 retenidoPool, bool bonoActivacion)',
  'function penalizacionesAcumuladas(address) view returns (uint256)',
  'function cancelAdminAction(uint256 id)',
  'event AdminActionProposed(uint256 indexed id, address indexed proposer, bytes4 selector, uint256 eta)',
  'event AdminActionConfirmed(uint256 indexed id, address indexed admin, uint256 confirms)',
  'event AdminActionCancelled(uint256 indexed id, address indexed admin)',
  'event AdminActionExecuted(uint256 indexed id, bytes4 selector)',
  'event HumanoVerificado(address indexed usuario)',
  'event OwnerTransferred(address indexed previousOwner, address indexed newOwner)',
  'event FundadorUpdated(address indexed previous, address indexed next)',
  'event Paused(address account)',
  'event Unpaused(address account)',
];
