sonar.sources=utils,wallet,web
sonar.tests=
sonar.test.inclusions=**/pruebas_*.py
sonar.exclusions=**/node_modules/**, **/venv/**, **/.venv/**, **/dist/**, **/build/**, **/zk-contracts/**, **/artifacts/**, **/cache/**, **/*.json, **/*.lock, **/*.md
