sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=test,forge-test
sonar.test.inclusions=test/**/*.js,test/**/*.ts,forge-test/**/*.sol
sonar.exclusions=**/node_modules/**, **/venv/**, **/.venv/**, **/dist/**, **/build/**, **/zk-contracts/**, **/artifacts/**, **/cache/**, **/forge-out/**, **/forge-cache/**, **/lib/forge-std/**, **/android/**, **/ios/**, **/.expo/**, **/typechain-types/**, **/stubs/**, **/.env, **/.env.*, **/keystore.properties, **/.scannerwork/**, **/*.lock
sonar.coverage.exclusions=test/**,forge-test/**,scripts/**,i18n/**,plugins/**,**/*.py
sonar.cpd.exclusions=i18n/locales/**,test/**,scripts/**,**/*.py
